### ISSUE TITLE
能不能自定义Exception

### ISSUE THREAD

**Issue by thundeGG** [zhou-you/RxEasyHttp#100]
大佬你好，callback的onError()方法的参数固定死了ApiException，希望这里可以优化下，我想根据自己的业务处理下Exception

**Comment by zhou-you** [comment]
你可以根据错误码自己定义

**Comment by 7hundeR** [comment]
怎么统一处理每一个请求，有点不太明白

**Comment by zhou-you** [comment]
返回的错误都有错误码，而且常见的异常都会有破获，除非个别的是 未知

**Comment by 7hundeR** [comment]
大佬，我想自定义callback，然后onError里走自己定义的Exception，这样怎么实现，如果是根据错误码去判断，那我需要每个请求都做个判断吗

**Comment by zhou-you** [comment]
不需要啊CallBack里面可以获取getCode()

**Comment by bailibaili** [comment]
> 不需要啊CallBack里面可以获取getCode()

我也遇到了同样的问题。
情况是这样的：现在想统一一个错误的message，比如只要是HTTPException，那么message都为“网络异常”，现在的问题是没有暴露出更改message的方法，所以只能再封装一层
