### ISSUE TITLE
POST中文问题

### ISSUE THREAD

**Issue by xxzztt** [zhou-you/RxEasyHttp#101]
POST中文到服务器变成了编码，需要解码才能用。
ajax POST不会变。没找到哪里设置的。

**Comment by xxzztt** [comment]
@POST()
    @FormUrlEncoded
    @Headers("Content-Type:application/x-www-form-urlencoded; charset=utf-8")
    Observable<ResponseBody> post(@Url String url, @FieldMap Map<String, String> maps);

这样能解决问题，关键是全局设置 Content-Type 为什么不起作用呢？

**Comment by zhou-you** [comment]
中文是必须要编码的，服务器是要解码的，请知悉，不编码中文会是乱码，所有网络通用的做法，不是本网络库才这么做。

**Comment by xxzztt** [comment]
可能我没有表达清楚。 主要是 如何修改Content-Type 的问题。不改组件代码的情况下好像不能把Content-Type 修改为 application/x-www-form-urlencoded; charset=utf-8 。我是通过修改接口，加上了@headers解决的。
"Content-Type:application/x-www-form-urlencoded; charset=utf-8"
