### ISSUE TITLE
感觉 ApiResult 真的不好用，或者说不会用。。。

### ISSUE THREAD

**Issue by g754687222** [zhou-you/RxEasyHttp#103]
是不可以用 addConverterFactory(GsonConverterFactory.create())。
 个人觉得大多数的开发者只想传入String或者自己根据JSON生成的实体，通过callback返回，自己判断数据里的code。

**Comment by zhou-you** [comment]
文档都有讲解，是因为使用前没有认真的看文档，上来就开始使用，wiki还有demo都有很详细的讲解。对OkHttp或者retrofit不是很了解的，基础不是很扎实的，最好先看文档然后再动手。
