### ISSUE TITLE
android:allowBackup参数

### ISSUE THREAD

**Issue by sweet2o09** [zhou-you/RxEasyHttp#106]
android:allowBackup="true"
这个能去掉么,会提示存在备份风险

**Comment by ymx91** [comment]
替换这个·就可以了   
<application
        android:name=".Application"
        android:allowBackup="false"
        tools:replace="android:allowBackup">

**Comment by ymx91** [comment]
<application
        android:name=".Application"
        android:allowBackup="false"
        tools:replace="android:allowBackup">

**Comment by sweet2o09** [comment]
ok
