### ISSUE TITLE
登录不成功怎么回事

### ISSUE THREAD

**Issue by guohaosir** [zhou-you/RxEasyHttp#11]

**Comment by Noah1991** [comment]
因为这是一个Demo，没有后台，你登录到哪？

**Comment by mackkill** [comment]
楼主你有在网页输入这个链接吗？ （尴尬脸，下次开车提前说下）
http://www.xxx.com/v1/account/login

今天闲着没事在公司输入这个链接，我是真的真的很尴尬。记住要开着 “梯子” ！！！

**Comment by zhou-you** [comment]
上传demo时把地址屏蔽掉了，如果有需要请联系我，demo都是已经调试通过的
