### ISSUE TITLE
ApiResult中的数据怎么获取

### ISSUE THREAD

**Issue by liangtian123** [zhou-you/RxEasyHttp#116]

**Comment by liangtian123** [comment]
比如，我要在onSuccess回调方法里拿到ApiResult里的messsage的值来判断，然后才能进行下一步

**Comment by zhou-you** [comment]
onSuccess里拿不到message除非你用String类型，message code属于onError信息，对于成功来说message很少有用

**Comment by liangtian123** [comment]
我就是要在onError里拿，服务端返回的状态码是400，响应体如下，我自定义了ApiResult，但是字段和你的ApiResult不一样，这样是不是没办法拿？
{
    "message": "already a staff",
    "status": "238"
}

**Comment by liangtian123** [comment]
这是成功时返回的json格式：
{
    "message": "Ok",
    "status": "0"
}

**Comment by liangtian123** [comment]
我是想在onError里拿到message给用户一个准确的回馈，而不是仅仅报错400

**Comment by zhou-you** [comment]
可以拿到你看下我的自定义数据结构我的是msg字段 你的是message字段，需要一个转换关系就可以实现拿到了，你看我的wiki里讲解，你这个问题完全可以解决满足

**Comment by zhou-you** [comment]
你要看文档，自定义数据结构都有讲解

**Comment by zhou-you** [comment]
https://github.com/zhou-you/RxEasyHttp/wiki/ApiResult
