### ISSUE TITLE
返回结果中Date类型字符转成Date时报错

### ISSUE THREAD

**Issue by 844189873** [zhou-you/RxEasyHttp#121]
服务器端返回的时间字符格式为“yyyy-MM-dd HH:mm:ss”时，ApiResultFunc将时间字符串转成Date时会报错。但ApiResultFunc在构造的时候初始化了gson，外部如何才能注册这个gson的时间转换格式？

ApiResultFunc的构方法如下：
    public ApiResultFunc(Type type) {
        gson = new GsonBuilder()
                .excludeFieldsWithModifiers(Modifier.FINAL, Modifier.TRANSIENT, Modifier.STATIC)
                .serializeNulls()
                .create();
        this.type = type;
    }

现在知道的解决办法是，业务里面的时间类型的字段直接使用字符串。如果自己的bean里面的时间要使用Date格式，这个没有办法解决？

**Comment by zhou-you** [comment]
默认为了统一是采用String处理
