### ISSUE TITLE
如何通过EasyHttp获取图片验证码？

### ISSUE THREAD

**Issue by mycone** [zhou-you/RxEasyHttp#123]
APP注册的时候会有一个图片验证码，这个验证码是一个URL地址，访问这个URL地址得到的是一个图片，我如何获取这个图片并展示到APP上呢？我是新手麻烦了。。。

**Comment by mycone** [comment]
实现了！！代码如下：
`private void getCaptcha(){
        final CustomRequest request = EasyHttp.custom().build();
        RegisterService mRegisterService = request.create(RegisterService.class);
        Call<ResponseBody> call = mRegisterService.captcha();
        call.enqueue(new Callback<ResponseBody>() {
            @Override
            public void onResponse(Call<ResponseBody> call, Response<ResponseBody> response) {
                try {
                    byte[] data = response.body().bytes();
                    Bitmap bitmap = BitmapFactory
                            .decodeByteArray(data, 0, data.length);
                    iv_code.setImageBitmap(bitmap);
                } catch (Exception e) {
                    HttpLog.e(e.getMessage());
                    e.printStackTrace();
                }
            }

            @Override
            public void onFailure(Call<ResponseBody> call, Throwable t) {
                t.printStackTrace();
            }
        });
    }`

**Comment by mycone** [comment]
`private void getCaptcha(){
        final CustomRequest request = EasyHttp.custom().build();
        RegisterService mRegisterService = request.create(RegisterService.class);
        Call<ResponseBody> call = mRegisterService.captcha();
        call.enqueue(new Callback<ResponseBody>() {
            @Override
            public void onResponse(Call<ResponseBody> call, Response<ResponseBody> response) {
                try {
                    byte[] data = response.body().bytes();
                    Bitmap bitmap = BitmapFactory
                            .decodeByteArray(data, 0, data.length);
                    iv_code.setImageBitmap(bitmap);
                } catch (Exception e) {
                    HttpLog.e(e.getMessage());
                    e.printStackTrace();
                }
            }

            @Override
            public void onFailure(Call<ResponseBody> call, Throwable t) {
                t.printStackTrace();
            }
        });
    }`

**Comment by mycone** [comment]
> 源代码：

private void getCaptcha() {

        final CustomRequest request = EasyHttp.custom().build();

        RegisterService mRegisterService = request.create(RegisterService.class);

        Call<ResponseBody> call = mRegisterService.captcha();

        call.enqueue(new Callback<ResponseBody>() {

            @Override
            public void onResponse(Call<ResponseBody> call, Response<ResponseBody> response) {
                try {
                    byte[] data = response.body().bytes();
                    Bitmap bitmap = BitmapFactory
                            .decodeByteArray(data, 0, data.length);
                    iv_code.setImageBitmap(bitmap);
                } catch (Exception e) {
                    HttpLog.e(e.getMessage());
                    e.printStackTrace();
                }
            }

            @Override
            public void onFailure(Call<ResponseBody> call, Throwable t) {
                t.printStackTrace();
            }
        });
    }

**Comment by zhou-you** [comment]
获取图片是要下载吗，可以用完全自定义CustomRequest

**Comment by zhou-you** [comment]
这个Url图片 然后你要下载图片吧
