### ISSUE TITLE
怎么addCookies?

### ISSUE THREAD

**Issue by tmxd09887** [zhou-you/RxEasyHttp#124]
EasyHttp.get(getUrl).baseUrl(baseUrl).addCookies(mCookieList)...
这里addCookies无效

cookieStore.saveFromResponse(httpUrl, cookieList);
README例子里的也无效

单个添加cookie是正常的，但是List 这种怎么添加？

**Comment by zhou-you** [comment]
是不是你addCookies(mCookieList)...添加的有问题。单个cookie添加的写法是如下：
 Cookie.Builder builder = new Cookie.Builder();
        Cookie cookie = builder.name(name).value(value).domain(httpUrl.host()).build();
        this.cookies.add(cookie);
