### ISSUE TITLE
有些机器会报java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by yuzhentao** [zhou-you/RxEasyHttp#127]
问题出在这个方法，也就是Context为null，但是明明在Application中初始化了还是会提示Context为null。
private static void testInitialize() {
 if (sContext == null)
  throw new ExceptionInInitializerError("请先在全局Application中调用 EasyHttp.init() 初始化！");
}
解决方法是先调用EasyHttp.getContext()判断一下，然后捕获掉异常。
try {
 if (EasyHttp.getContext() == null)
 return;
//Your code
} catch (Exception e) {
 e.printStackTrace();
}

**Comment by zhou-you** [comment]
这个问题其他人还没反馈过，我会留意下，理论上不应该，除非是停留太久被回收了，不然不可能存在这个问题
