### ISSUE TITLE
您好，后台请求把错误信息放在了errorbody里面，用了您的框架，走了onError的回调，但是在ApiException里面拿不出errorBody

### ISSUE THREAD

**Issue by liangtian123** [zhou-you/RxEasyHttp#128]

**Comment by liangtian123** [comment]
已解决（之前在同一个问题得到的答案，我以为用不了，结果发现是我导错包了而已）：
if (e.getCause() instanceof HttpException)
HttpException httpException = (HttpException) e.getCause();
httpException.response().errorBody().string()

**Comment by zhou-you** [comment]
OK 问题解决就好
