### ISSUE TITLE
CallBackProxy代理

### ISSUE THREAD

**Issue by AIlll** [zhou-you/RxEasyHttp#13]
自定义ApiResult通过CallBackProxy代理直接返回我们需要的Bean对象，那我们还能拿到Bean对象外层的数据吗，比如code，msg

**Comment by zhou-you** [comment]
拿不到了

**Comment by AIlll** [comment]
@zhou-you 请问文件下载可以结合rxjava吗

**Comment by zhou-you** [comment]
你好你是想怎么与rxjava结合

2017-10-25 12:00 GMT+08:00 AIlll <notifications@github.com>:

**Comment by AIlll** [comment]
@zhou-you debug日志开关打开了，之前可以看到详细的日志，现在就成这样了，怎么回事
![image](https://user-images.githubusercontent.com/23742136/33822810-de368d34-de93-11e7-846f-c38a3ce246a2.png)

**Comment by AIlll** [comment]
@zhou-you 关于数据解析，{code:1,msg:验证失败,result:null}，类似这种，onError中回调的exception始终都会是空指针异常，因为result字段是按对象来解析的，onError我想拿到code和msg该怎么做

**Comment by jingquanxie** [comment]
@zhou-you 有办法通过其他方式拿到code和msg么？因为有时候需要这个code比如，token超时的时候一般是通过code判断的

**Comment by AIlll** [comment]
@jingquanxie 加一个拦截器就好了，在拦截器里面获取code

**Comment by jingquanxie** [comment]
有道理，多谢，刚好你在，再问你个问题，不知道什么原因，我的一个请求直接发起了两次请求，我已经关闭了，重复请求的，看日志：


![qq 20180103103443](https://user-images.githubusercontent.com/7383365/34507513-bd21fd5a-f071-11e7-83ae-012931fe576e.png)

有交流群么？

**Comment by AIlll** [comment]
@jingquanxie 我之前也会出现两次，不过是因为我在拦截器动态添加了请求参数，发出了新的请求，就会有两遍请求
