### ISSUE TITLE
onCompleted是不是无论onSuccess，onError后面都会调用？

### ISSUE THREAD

**Issue by bean-liu** [zhou-you/RxEasyHttp#132]
因为我是在onCompleted中把loading效果去掉，但是来个500的错误之后在调了onError之后却没有调用onCompleted？？？

```
HttpManager.get(API_URL.XXX)
                .params(httpParams)
                .execute(new SimpleCallBack<List<ResponXXX>>(){...}
```
HttpManager是用的你demo里的

> 根据自定义请求写一个请求的管理类方便调用
  作者： zhouyou
  日期： 2017/7/7 10:31 
  版本： v1.0

**Comment by zhou-you** [comment]
是的

**Comment by bean-liu** [comment]
@zhou-you 如果是的话那就不正常了

**Comment by zhou-you** [comment]
调用回调的方法onCompleted 切记点开我的代码看看，如果我的库里面也有调用onCompleted进行处理，但是你外面覆写的时候去掉了super.onCompleted()造成我里面一些代码没有起作用，这个也是初学者容易犯的错误，你注意检查下。
