### ISSUE TITLE
怎么控制只有wifi 下请求接口，4g 状态下不请求？

### ISSUE THREAD

**Issue by bingdu0** [zhou-you/RxEasyHttp#136]
为什么没有网络状态的判断呢？

**Comment by zhou-you** [comment]
网络状态自己在上次判断呀，或者自己内置一个网络判断的拦截器，请理解一点就是我的库不是服务于某个人的也不是某个人特殊场景，今天你有控制wifi下请求接口的，其它很多人很多市面上的app都不会有这个需求吧，顶多是视频播放才有这个wifi和4G流量的提醒，请正确看待一个问题！
