### ISSUE TITLE
返回加密的byte数据错误

### ISSUE THREAD

**Issue by Hemumu** [zhou-you/RxEasyHttp#139]
服务器返回一段加密的byte，在ApiResultFunc中通过responseBody.bytes()拿到数组发现数据变了，请问是对byte做了什么处理么！

**Comment by Hemumu** [comment]
问题已经解决，如果服务器返回3DES 加密的byte数组，  由于在.debug()方法中设置了isPrintException参数为true，默认会加一个HttpLoggingInterceptor拦截器，而在拦截器中的logForResponse方法中调用了String body = responseBody.string();  和 responseBody = ResponseBody.create(responseBody.contentType(), body); 这两句代码，导致byte数组错乱，以致于不能解码，修改为  byte[] bs = responseBody.bytes();
                        String body = new String(bs,"UTF-8");
                        log("\tbody:" + body);
                        responseBody = ResponseBody.create(responseBody.contentType(), bs);  问题解决，这问题也挺坑的。

**Comment by zhou-you** [comment]
问题解决了就好
