### ISSUE TITLE
自定义分页数据解析问题

### ISSUE THREAD

**Issue by abcdisgreat** [zhou-you/RxEasyHttp#140]
分页查询时定义的统一的接收

![image](https://user-images.githubusercontent.com/33865977/55042389-2c36f500-506c-11e9-8b93-3f10cceeb9d8.png)

在接收时无法成功解析

**Comment by zhou-you** [comment]
这个是数据泛型的泛型导致的数据丢失，也就是泛型擦除问题，你可以了解下

**Comment by abcdisgreat** [comment]
要是像 List<A> data;  List<B> data;这样每个都定义一个model能避免擦除，有什么更好方法能解决呢

**Comment by zhou-you** [comment]
暂时没有好的办法，或者用String接收自己解析

**Comment by abcdisgreat** [comment]
@zhou-you 还有一个小问题，
public R params(String key, String value) {
        params.put(key, value);
        return (R) this;
    }

请求传参能否优化成直接可以传数值类型的，不然每个参数都有转一下String

**Comment by Jimmuy** [comment]
> @zhou-you 还有一个小问题，
> public R params(String key, String value) {
> params.put(key, value);
> return (R) this;
> }
> 
> 请求传参能否优化成直接可以传数值类型的，不然每个参数都有转一下String

同样疑惑params为什么不设计成String,Object这种键值对形式，而是string,string这种
