### ISSUE TITLE
EasyHttp.downLoad 下载word

### ISSUE THREAD

**Issue by lovehua** [zhou-you/RxEasyHttp#142]
EasyHttp.downLoad 下载word 打开错误 是怎么回事

**Comment by zhou-you** [comment]
是不是编码的问题导致的

**Comment by lovehua** [comment]
应该不是 通过直接通过浏览器下载的 就可以正常查看 我用咱们测试 例子 也测试了一下， 下载后的文件也损坏（word，ppt等），其他的很正常

**Comment by zhou-you** [comment]
很有可能还是编码的问题，这个下载只是下载普通的文件图片，apk包，文本等，word、ppt格式理论上也是可以支持的，如果打开错误可能就是编码导致的，word里面内容的编码，你是否可以测试里面写个简单的内容，例如“1233446” “abcd”等 先不要中文等其它内容，再测试下基本就知道问题了。
