### ISSUE TITLE
这个框架在onError回调中怎么拿到后台返回的message啊?

### ISSUE THREAD

**Issue by ZHLhenry** [zhou-you/RxEasyHttp#144]
![WX20190410-211753](https://user-images.githubusercontent.com/22535380/55881977-47f6db00-5bd6-11e9-95ee-15a506847740.png)
这个自己后台服务器的code都能拿到.为什么这个message拿不到啊? 这个框架有什么方法可以拿到么?   如果在成功回调里面这个有办法拿到,关键是最后回调是走在了onError里面ApiException e  e.getMessage拿不到值

**Comment by zhou-you** [comment]
是可以拿到的，你要看下自定义数据结构https://github.com/zhou-you/RxEasyHttp/wiki/ApiResult_New，我的错误信息是通过msg字段返回回去的，你的字段是message,通过自定义数据结构就可以拿到了，先看下文档就明白了。
