### ISSUE TITLE
为什么我请求成功了 还是会走onError方法,

### ISSUE THREAD

**Issue by wangJeft** [zhou-you/RxEasyHttp#146]
![image](https://user-images.githubusercontent.com/29792634/56123063-4cd8d780-5fa6-11e9-91f0-1dc1d880f9f8.png)
为什么我请求成功了 还是会走onError方法,

**Comment by amosxb** [comment]
你的code不是200啊

**Comment by zhou-you** [comment]
了解下自定义数据结构，我的code默认是0表示成功
