### ISSUE TITLE
参数传Map<String,String>可否多个重载Map<String,Object>

### ISSUE THREAD

**Issue by svran** [zhou-you/RxEasyHttp#147]
EasyHttp.get(URL).params(Map<String,Object>)....
这样参数更方便直接传 int,float,String等,其他的类直接toString()

**Comment by zhou-you** [comment]
如果是int或者float你当成 string处理就行了

**Comment by zhou-you** [comment]
其他类直接toString()还是string呀

**Comment by svran** [comment]
@zhou-you  非常好的库,我已经down下来根据自己项目中的情况,修改相应的返回数据结构,参数传递这些问题了.感谢你的开源!
我这里遇到返回数据结构是: 
请求正常:
{
"ok":true,
"message":{...data...}
}
token过期:
{
"ok":false,
"message":{"Result":"token过期","IsExpired":true}
}
其他错误:
{
"ok":false,
"message":"错误信息"
}
这类奇葩的返回数据结构,只能自己整咯.

**Comment by zhou-you** [comment]
你这个可以不用down代码，你可以自定义数据结构，在isOK里面重写 我里面是用code==XX表示成功，你可以直接用你的ok 布尔值来表示是否成功

**Comment by svran** [comment]
@zhou-you  其实吧,问题就出在 message 在业务逻辑正确的请求中,返回的是bean,业务逻辑错误的时候返回的是string. 

当然我自定义过用ok表示成功与否,code其实在这里随便多少也无所谓,msg错误信息就不好处理了.
如果message用String message,在业务逻辑正确的时候就报json转换异常;
如果message用T message,那业务逻辑错误的时候就报null异常;

我目前只能修改 com.zhouyou.http.func.ApiResultFunc.java 这个文件,自己解析json,返回ApiResult;
![image](https://user-images.githubusercontent.com/13031351/56880978-71967a00-6a91-11e9-8e1d-744446604f92.png)

另外参数加一个Map<String,Object>类型的:
com.zhouyou.http.request.BaseRequest.java
![image](https://user-images.githubusercontent.com/13031351/56881065-c934e580-6a91-11e9-8626-2b67f29abd2d.png)

**Comment by zhou-you** [comment]
也可以

**Comment by liangtian123** [comment]
这种情况，如果你是用Gson解析数据，还可以注册一个Deserializer来自定义解析数据
![image](https://user-images.githubusercontent.com/29178702/62445544-0b597b80-b793-11e9-8c93-c3ec367a72d4.png)
