### ISSUE TITLE
请求自定义结果回调不懂请教一下

### ISSUE THREAD

**Issue by abcdisgreat** [zhou-you/RxEasyHttp#148]
CallBack回调 成功只传了data，现在想拿到成功的msg，看文档提到**自定义CallBack回调
如果对回调有特殊需求，支持可以继承CallBack自己扩展功能**，但是demo好像没举例子，没搞懂怎么扩展，如何才能拿到成功的msg。
然后是 onError 时的ApiException，这个异常里的定的错误码100x这些很容易会和后台定的错误码冲突，请求错误时会误操作

**Comment by zhou-you** [comment]
成功的msg是拿不到的，成功了你的数据定义msg会对应很多个吗，一般msg是在错误才返回。如果要拿到msg只能返回String自己解析。
