### ISSUE TITLE
建议把CacheResult 的toString改一下，我不知道有这个必要吗？

### ISSUE THREAD

**Issue by LeslieKoma** [zhou-you/RxEasyHttp#15]
return "{" +
                "\"isCache\":" + isFromCache +
                "," + "\"data\":" + data +
                '}';

**Comment by zhou-you** [comment]
这个是调试的时候使用的，加toString对使用没影响吧！，有什么问题呢

**Comment by zhou-you** [comment]
你好，请问你出现什么具体的问题了呢

2017-09-27 16:56 GMT+08:00 LeslieKoma <notifications@github.com>:
