### ISSUE TITLE
未知错误

### ISSUE THREAD

**Issue by YangLzy** [zhou-you/RxEasyHttp#153]

**Comment by YangLzy** [comment]
从2.1.0升级到2.1.5时候，线上报错未知错误，抓包看没有发起http请求，有什么解决方案吗？
e !instanceof ApiException err 未知错误

**Comment by zhou-you** [comment]
1.是不是正式版本混淆的问题  2.检查数据结构后台服务器接口参数以及返回的内容是否有变化

**Comment by YangLzy** [comment]
你好，代码未混淆，这个错误偶尔发生；发生后无法恢复

**Comment by YangLzy** [comment]
找到问题了，是一个参数偶尔传空值，导致的这个未知错误；期待下一版本兼容下参数空值或明确打印出错误原因
