### ISSUE TITLE
关于kotlin环境下使用的错误反馈

### ISSUE THREAD

**Issue by ningsk** [zhou-you/RxEasyHttp#155]
![image](https://user-images.githubusercontent.com/16011421/57593998-88989a00-7570-11e9-98db-c9fd9833b760.png)

之前使用java环境的时候 data 为 List<Shop>是可以的，可是将代码转化为kotlin之后，
会出现转换异常。java.lang.ClassCastException: com.google.gson.internal.$Gson$Types$WildcardTypeImpl cannot be cast to java.lang.Class

**Comment by zhou-you** [comment]
暂时没有做针对kotlin的，针对这个错误可以自己处理下

**Comment by ningsk** [comment]
嗯，我自己处理了一下，在simpleCallback里面做了二次封装处理，处理了这个问题。
谢谢回复。

**Comment by BeetleSxy** [comment]
@ningsk 你好可以告诉一下你是如何处理的吗？以作参考

**Comment by kilo-swodh** [comment]
没想到对kotlin支持不够

**Comment by xiongxiaosong** [comment]
> 嗯，我自己处理了一下，在simpleCallback里面做了二次封装处理，处理了这个问题。
> 谢谢回复。

可以说一下怎么处理的吗
