### ISSUE TITLE
OkHttpClient多实例

### ISSUE THREAD

**Issue by everhad** [zhou-you/RxEasyHttp#159]
com.zhouyou.http.request.BaseRequest#okHttpClient
我Debug发现每次请求都会是新的BaseRequest对象，这样就每次都会产生一个不同的okHttpClient实例？
okHttpClient 建议是共享的，这可能是很大的性能问题呀？

来自官网：
Factory for calls, which can be used to send HTTP requests and read their responses.
OkHttpClients should be shared
OkHttp performs best when you create a single OkHttpClient instance and reuse it for all of your HTTP calls. This is because each client holds its own connection pool and thread pools. Reusing connections and threads reduces latency and saves memory. Conversely, creating a client for each request wastes resources on idle pools.

**Comment by zhou-you** [comment]
okHttpClient  是共享的，除非有个性化的请求，里面会智能判断重新new okHttpClient
