### ISSUE TITLE
如果全局有三个baseurl就难搞了，总不可能每个请求都去拼接吧

### ISSUE THREAD

**Issue by PingerOne** [zhou-you/RxEasyHttp#16]
如题，多个baseurl如何统一请求呢，大神赐教~

**Comment by zhou-you** [comment]
不用拼接啊，文档中有url的讲解，如下:
![image](https://user-images.githubusercontent.com/15211403/31531682-1670a0e2-b01b-11e7-9e1e-afc14ea3a100.png)

**Comment by zhou-you** [comment]
设计的时候是这么考虑的，全局请求只能设置一个，就是你的应用里大部分接口都会使用到的，局部baserul就是个性化请求，也就是请求地址开头和全局设备的不一样。

2017-10-09 22:22 GMT+08:00 Pinger <notifications@github.com>:
