### ISSUE TITLE
建议:1.同步请求不应把结果放在回调中、返回值应该立即返回 2. 框架的okhttp版本和rxjava第三方框架的版本建议升级一下

### ISSUE THREAD

**Issue by Liby94** [zhou-you/RxEasyHttp#164]

**Comment by zhou-you** [comment]
1.同步请求你们可以直接返回obsrvable 2.你们现在主要用的是哪个版本的，用最新的也不合适

**Comment by Liby94** [comment]
@zhou-you 
因为是以前别人写的代码，同步请求的结果需要做为返回值return回去、在同步回调中赋值后return是没有问题的、但是感觉写法看起来有点怪、我看了Nohttp的库同步请求也是直接返回，没有使用回调的方式。同步请求需要返回值的这种情况写的时候就好写一点了

另外感觉ApiResult对bean类的侵入性有点强

okhttp版本前一段时间项目升级了3.11版本、RxEasyHttp当前用的是3.4的版本，希望框架的依赖库也可以慢慢的更新依赖版本、不用保持最新、我对比了其它的网络封装库，基本上都是3.10版本后的

写的有点乱、我不会封装代码、有些理解错误说错了大佬莫生气   ( ^_^ )

**Comment by zhou-you** [comment]
第一个返回同步的，后期可以优化下，第二个问题我会对库引用的版本进行升级
