### ISSUE TITLE
对于全局请求参数，希望增加全局的是否签名，是否加token，是否加时间戳的开关

### ISSUE THREAD

**Issue by bailibaili** [zhou-you/RxEasyHttp#166]
因为现在是默认关闭的，所以如果可以设置默认开启的话，会比较灵活，真正做到动态。
不知道对您的框架理解对不对，还是说有支持全局开启的方法呢？

**Comment by zhou-you** [comment]
因为应用当中加签名的接口相对来说说是比较少的，不是所有接口都需要增加签名，签名只是考虑个性化的个别需求，通过设置就行了，没必要增加全局设置的开关
