### ISSUE TITLE
全局请求头打印不出来的问题

### ISSUE THREAD

**Issue by bailibaili** [zhou-you/RxEasyHttp#167]

**Comment by zhou-you** [comment]
库里面已经做了头的打印，你可以看下HttpLoggingInterceptor.java类125行

**Comment by bailibaili** [comment]
> 库里面已经做了头的打印，你可以看下HttpLoggingInterceptor.java类125行

- 是的，但是应该是添加顺序原因，所以所有的请求头都是无法打印的。我自己重写了，谢谢

**Comment by zhou-you** [comment]
ok,可以把拦截器最后添加
