### ISSUE TITLE
单独使用RxCache，打包时多处警告，麻烦大神抽时间改一下

### ISSUE THREAD

**Issue by wgheng** [zhou-you/RxEasyHttp#17]
C:\Android\Work\XXX\app\src\main\XXX\cache\RxCache.java
Error:(118, 36) 警告: [unchecked] 未经检查的转换
需要: Class<T>
找到:    Class
其中, T是类型变量:
T扩展已在方法 <T>transformer(CacheMode,Type)中声明的Object
C:\Android\Work\XXX\app\src\main\XXX\cache\converter\SerializableDiskConverter.java
Error:(49, 39) 警告: [unchecked] 未经检查的转换
需要: T
找到:    Object
其中, T是类型变量:
T扩展已在方法 <T>load(InputStream,Type)中声明的Object
C:\Android\Work\XXX\app\src\main\XXX\cache\converter\GsonDiskConverter.java
Error:(78, 37) 警告: [unchecked] 未经检查的转换
需要: T
找到:    CAP#1
其中, T是类型变量:
T扩展已在方法 <T>load(InputStream,Type)中声明的Object
其中, CAP#1是新类型变量:
CAP#1从?的捕获扩展Object

**Comment by zhou-you** [comment]
build.gradle  android { } 里增加
`lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }`

**Comment by wgheng** [comment]
@zhou-you 我的build文件里之前已经添加过这两条lintOptions了，貌似对这个错误警告不起作用

**Comment by wgheng** [comment]
加了抑制警告注解，暂时先这样了。  很感谢博主的分享
