### ISSUE TITLE
某些手机缓存无效

### ISSUE THREAD

**Issue by TakeNotes2019** [zhou-you/RxEasyHttp#174]
我手上的几个真机，荣耀与小米 都可以缓存，断网后也使用之前请求成功的数据。
而vivo  无法缓存， 断网后 没有返回之前请求成功的数据

**Comment by zhou-you** [comment]
你好，这个问题解决了吗，可以断点查看下，我这边也注意下这个问题

**Comment by TakeNotes2019** [comment]
你好！这个问题主要出在 缓存设置的参数那里，CACHEANDREMOTE，CACHEANDREMOTEDISTINCT这两个参数，在vivo上 就是不行，而在另一台手机上还有一个问题就是，连网的时候，缓存到了数据，在打开飞行模式后，第一次显示使用了缓存参数，返回再调用 就缓存参数没了，我猜想是 没请求到参数后 把我的原来缓存的参数 也给替换了

**Comment by zhou-you** [comment]
缓存的key必须是要唯一的呀，怎么会发生替换呢

**Comment by TakeNotes2019** [comment]
这个问题，本来是有缓存数据的，但是后来网络没获取到数据， 把空给赋值到缓存里面了
，这么久了， 我忘了当时 出现这个情况的环境是什么样的了， 但是后来 我用了另外一种缓存方式， 就给交差 了
