### ISSUE TITLE
约定异常 Error与后台返回特殊状态码冲突了,请求指点

### ISSUE THREAD

**Issue by wongyue** [zhou-you/RxEasyHttp#175]
```
 /**
     * 约定异常
     */
    public static class ERROR { 
       public static final int UNKNOWN = 1000;
    }
```
1000 - 1004 这几个值后台返回的有对应情况，和这个约定的错误状态码冲突，整个网络请求基本用的这个库，有没啥好的思路，望指点指点

**Comment by zhou-you** [comment]
你可以通过错误里面ApiException异常类型来判断是我本地的 还是来自服务器的
例如：.execute(new SimpleCallBack<String>() {
                    @Override
                    public void onError(ApiException e) {
                        if(e instanceof ServerException ||e instanceof HttpException){
                            //说明是来自服务器 不是本地的异常
                        }
                        
                        showToast(e.getMessage());
                    }

                    @Override
                    public void onSuccess(String response) {
                        showToast(response);
                    }
                });

**Comment by wongyue** [comment]
ok  老哥  非常感谢🤗
