### ISSUE TITLE
大佬你这个库完全可以就用rxjava+okhttp实现啊，没必要引入Retrofit 啊

### ISSUE THREAD

**Issue by zomll** [zhou-you/RxEasyHttp#177]
你的 基础ApiService 把Retrofit的优势给干掉了啊，干嘛不用okhttp来提供get，post方法呢，你这个库里引入Retrofit意义何在？

**Comment by zhou-you** [comment]
Retrofit是Square公司出品的默认基于OkHttp封装的一套RESTful网络请求框架，RESTful是目前流行的一套api设计的风格， 并不是标准。Retrofit的封装可以说是很强大，里面涉及到一堆的设计模式,可以通过注解直接配置请求，可以使用不同的http客户端，虽然默认是用http ，可以使用不同Json Converter 来序列化数据，同时提供对RxJava的支持，使用Retrofit + OkHttp + RxJava + Dagger2 可以说是目前比较潮的一套框架. 还有库不满足需求的时候，里面高级自定义部分提供可以用回Retrofit ，自己写请求接口，然后配合RxEassyHttp使用。

**Comment by zhou-you** [comment]
当然不用也是可以的
