### ISSUE TITLE
自定义数据结构ApiResult

### ISSUE THREAD

**Issue by littlezan** [zhou-you/RxEasyHttp#18]
当服务端返回的code是String类型的时候，会报错，请问如何兼容了。
是否可以将ApiResult 修改成通过实现接口的方式，在ApiResultFunc中只要调用接口就行，这样自定义ApiResult是，只需要实现想用的接口即可？
我现在是直接自定义了PostRequest类，然后再自定义ApiResultFunc类，自己处理了

**Comment by zhou-you** [comment]
ApiResult 目前code是int 不支持String，有计划对反应的问题，重构一个版本

**Comment by zhou-you** [comment]
自定义ApiResultFunc是可以的，就是比较麻烦一点，不过能解决问题

**Comment by littlezan** [comment]
嗯，谢谢
