### ISSUE TITLE
遇到后台返回的data为null时怎么解决啊？

### ISSUE THREAD

**Issue by eternallyjie** [zhou-you/RxEasyHttp#180]
后台返回数据有时没有数据的时候为null，但是rxjava2不逊于onNext为null，直接就到onError报NullPointException了，这时候该怎么解决呢？

**Comment by eternallyjie** [comment]
我在你的HandleFuc里面返回下面这样:
return tApiResult.getData()== null ? Optional.ofNullable(tApiResult.getData()).orElse(null) : tApiResult.getData();
这么修改之后还是一样的会报空指针。麻烦请问应该怎么返回null值呢？

**Comment by zhou-you** [comment]
处理这个比较麻烦你可以重写callback或者订阅，当出现空指针也让他走成功。
