### ISSUE TITLE
ApiResult<T> data =null 如何处理

### ISSUE THREAD

**Issue by TakeNotes2019** [zhou-you/RxEasyHttp#181]

**Comment by TakeNotes2019** [comment]
我自定义了 ApiResult ，data 回调的类型多种多样，有基本类型，也有自定义类型，也有list,有的时候服务器接口不需返回data 数据，只用code值判断就可以了，这个时候 返回的data=null,我该如何处理呢？

**Comment by TakeNotes2019** [comment]
我在 HandleFuc 里面看到 其实是有对data=null 判断了的，但是给注释了，不知道大神你是出于什么样的考虑 把他注释了呢

**Comment by TakeNotes2019** [comment]
HandleFuc里面我把 注释掉的判断  还原后   还是会 提示 空指针 。。 我不知道该如何解决了

**Comment by zhou-you** [comment]
data 不能为null 这个是Rxjava2 onNext方法决定的，不能为null，可以百度下
