### ISSUE TITLE
请问一下，如何在请求成功后获取header里面的内容？

### ISSUE THREAD

**Issue by lamandys** [zhou-you/RxEasyHttp#184]

**Comment by Jameshuihui** [comment]
同问

**Comment by zhou-you** [comment]
目前不支持header里面获取内容，从拦截器里面可以获取到

**Comment by lamandys** [comment]
这个问题，已经解决，在拦截器去获取请求成功后返回的header不实际，比较麻烦与耦合，我的解决办法是：直接更改库的代码，从源头出发，返回Observable<Response<ResponseBody>>，增加callback，方便实用

**Comment by zhou-you** [comment]
对这个是比较直接的，要增加返回header功能
