### ISSUE TITLE
我在post请求的时候如何修改参数提交方式（Content-Type）？

### ISSUE THREAD

**Issue by zhumj** [zhou-you/RxEasyHttp#185]
EasyHttp.post("user/login")
                .params("account", email)
                .params("password", password)
                .params("phoneCode", phoneCode)

我像上面添加参数的话对应的 表单（application/x-www-form-urlencoded） 提交，但我想改为 application/json 方式提交。

**Comment by zhumj** [comment]
找到方法了，使用 EasyHttp.post("user/login").upJson(json.toString()) 就可以，还是需要在文档里面提一下啊

**Comment by zhou-you** [comment]
文档应该有upJson方式提交的讲解吧

**Comment by zhumj** [comment]
说实话，很难找
