### ISSUE TITLE
大神，请求成功后我怎么拿到ApiResult的code值

### ISSUE THREAD

**Issue by TakeNotes2019** [zhou-you/RxEasyHttp#186]
大神，由于我的请求接口成功返回的code值不是 一个数值，而是9000-9999这个范围，所以在请求成功后，我希望能拿到这个code值和msg , 因为在产品设计的时候  ，即使u接口成功后，返回不同的值也须要不同的逻辑来做后续 操作流程。
请大神 指教！！！！！！

**Comment by zhou-you** [comment]
目前设计的是成功不返回code，后面可以扩展，暂时针对这种特别一点的接口你可以先返回String自己解析内容
