### ISSUE TITLE
如何把 ApiResult 的全部参数获取到，

### ISSUE THREAD

**Issue by TakeNotes2019** [zhou-you/RxEasyHttp#196]
在我当前的接口里面，某些接口为了做的 层级不是那么多，直接在 data 同级位子 增加了一些参数，甚至还有 实体类，， 比如说 返回的data 里面是一个列表， 接口做分页处理了， 然后就在data 同级的位置 增加了列表总数量  total 这个参数，而其他个别接口 还增加和data差不多的 实体类， 成了双列表 参数， 由于另外一个实体类并不是一直出现，只在某些条件的情况下才出现，， 使用现在就想知道 如何获取 ApiResult  下面的所有内容，，，，也许还有增加了自定义参数

**Comment by zhou-you** [comment]
这样的话直接返回String自己解析吧
