### ISSUE TITLE
泛型

### ISSUE THREAD

**Issue by softOfAndroid** [zhou-you/RxEasyHttp#2]
额外问个问题：假如参数不对，服务器返回json这样结构：
{
"code": 100010101,
"data": “”,
"msg": "参数不对"
}
正确服务器返回
{
"code": 100010101,
"data": {“X”:“x”},
"msg": "请求成功"
}
参数正确，请求也成功没错，但参数错误ApiResult中data为空，Retrofit2 + Rxjava2+Gson框架的解析有误，会走onError(@NonNull Throwable e)方法，但是我需要服务器返回的msg信息，怎么改呢
subscribe(new Observer<ApiResult<T>>() {
                        @Override
                        public void onSubscribe(@NonNull Disposable d) {
                        }
                        @Override
                        public void onNext(@NonNull ApiResult<T> result) {
                           
                        }
                        @Override
                        public void onError(@NonNull Throwable e) {
                            
                        }
                        @Override
                        public void onComplete() {
                           
                        }
                    })

**Comment by zhou-you** [comment]
这个Rxjava2是这样的，null的话要自己处理，网上有很多这样的解决办法。

2017-06-15 15:23 GMT+08:00 张小云 <notifications@github.com>:

**Comment by T-Merak** [comment]
@zhou-you 大神可以给一下参考连接吗?我找到貌似都感觉不怎么靠谱啊

**Comment by T-Merak** [comment]
@softOfAndroid 大佬你找到什么好的决解方案吗?

**Comment by zhou-you** [comment]
这个为null的，网上是有人处理，但是很复杂 成本很高

2017-09-15 17:07 GMT+08:00 T-Merak <notifications@github.com>:

**Comment by zhou-you** [comment]
可以做一个错误处理，在订阅中如果错误时空指针错误，去调用onSuccess或者onNext回调，增加判断

2017-09-18 9:09 GMT+08:00 周游 <zhouyou1989123@gmail.com>:

**Comment by T-Merak** [comment]
好吧我在网上找到的方案是从写一个拦截器自己解析json @zhou-you 但是不知道会不会出现性能消耗增加

**Comment by softOfAndroid** [comment]
@T-Merak 把服务器data返回“”改成返回null了
