### ISSUE TITLE
添加Headers咨询

### ISSUE THREAD

**Issue by LiaoZhuo** [zhou-you/RxEasyHttp#20]
你好！
       本人在使用RxEasyHttp时，遇到一个使用Interceptor执行顺序的问题。本人在发起请求时，加入了自定义的Header，同时也添加了一个需要处理自定义Headers的自定义Interceptor。问题就来了，在发起请求时，`BaseRequest`的方法`generateOkClient()`会加入自带的Interceptor，其中有个`HeadersInterceptor`，是用来把RxEasyHttp自定义的Headers加入到`OkHttpClient`的`Request`的headers中，，但是本人自自己添加的Interceptor始终在`HeadersInterceptor`之前执行，无论是在初始化RxEasyHttp还是在发起请求时，导致本人自定义的Interceptor无法拿到自定义的headers。
       然后，本人直接修改了源代码，直接在添加完`HeadersInterceptor`之后，又添加了自定义的Interceptor，于是问题得到解决。可是这样就修改了源代码，请问有什么好办法吗？
       谢谢。

**Comment by zhou-you** [comment]
你好，请问下提供的设置header是满足不了的对吧，所以你才自己扩展。如果可以尽量采用addHeader就不会出现这个问题。我会把源码修改下，把HeadersInterceptor拦截器放在最前面添加，这样其它拦截器就可以使用了。

**Comment by LiaoZhuo** [comment]
感谢你的回复，我知道了。
