### ISSUE TITLE
formBody好像不支持呢

### ISSUE THREAD

**Issue by AdminQQZ** [zhou-you/RxEasyHttp#208]

**Comment by zhou-you** [comment]
用我的库 你好像不会直接用到这个吧

**Comment by AdminQQZ** [comment]
后台需要这个请求方式。。formbody 来提交




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "周游"<notifications@github.com&gt;; 
发送时间: 2019年12月20日(星期五) 中午1:37
收件人: "zhou-you/RxEasyHttp"<RxEasyHttp@noreply.github.com&gt;; 
抄送: "867711323"<867711323@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhou-you/RxEasyHttp] formBody好像不支持呢 (#208)




用我的库 你好像不会直接用到这个吧

**Comment by AdminQQZ** [comment]
嗨，Okgo formBody的提交方式是  
 HttpParams mHttpParams= new HttpParams();
 mHttpParams.put("Sex", sex);
okgo.xxx.upRequestBody(HttpUtils.generateMultipartRequestBody(mHttpParams, true))
可以参考，添加上。谢谢大佬。

还有,可以获取缓存大小吗？,清理缓存。可以增加功能吗。嘻嘻

**Comment by zhou-you** [comment]
RequestBody也有，你可以看下demo，文件上传部分，参照
