### ISSUE TITLE
关于 回调中处理返回头部信息

### ISSUE THREAD

**Issue by zh-kevin** [zhou-you/RxEasyHttp#21]
关于业务结果中要在回调中处理返回头部信息 。这个支持吗？  看了源码是对 responseBody 的处理， 这个没办法获取到其他信息。

**Comment by zhou-you** [comment]
头信息，你可以自定义一个拦截器在里面处理

**Comment by zhou-you** [comment]
用要用拦截器处理

2017-10-21 16:37 GMT+08:00 kevin <notifications@github.com>:
