### ISSUE TITLE
登录不成功

### ISSUE THREAD

**Issue by jameschen4540** [zhou-you/RxEasyHttp#22]
登入不成功，是url问题么？

**Comment by zhou-you** [comment]
这个是自己的URL我屏蔽掉了，如有需要，请扫码进群联系我

**Comment by zhou-you** [comment]
已经修改成demo启动不需要登录

**Comment by zhou-you** [comment]
是的，为了安全我把url去掉了

2017-10-24 17:50 GMT+08:00 jameschen4540 <notifications@github.com>:
