### ISSUE TITLE
kotlin类里面调用解析list类型转换错误

### ISSUE THREAD

**Issue by xiongxiaosong** [zhou-you/RxEasyHttp#224]
kotlin类里面调用解析list类型转换错误
ApiService.getInstance().getMessage(object : SimpleCallBack<List<Message>>(){
override fun onSuccess(t: List<Message>) {
                Log.e("onSuccess","onSuccess")
            }
 override fun onError(e: ApiException) {
                super.onError(e)
                e.printStackTrace()
            }
})
同样的在java类里面调用正常
 ApiService.getInstance().getMessage(new SimpleCallBack<List<Message>>() {
                    @Override
                    public void onSuccess(List<Message> listResult) {

                    }
                })

**Comment by xiongxiaosong** [comment]
已经解决了

**Comment by johnyonghui** [comment]
> 已经解决了

你是怎么解决的呢？
