### ISSUE TITLE
混淆问题

### ISSUE THREAD

**Issue by yangqqq537** [zhou-you/RxEasyHttp#24]
body:------{"meta":{"code":"200","message":"正常"},"body":{"needUpdate":"0","token":"**********"}
 <-- END HTTP
10-26 14:00:01.620 29085-29085/? E/OperationTool:a.onError(L:-1): -->http is onError
10-26 14:00:01.622 29085-29085/? E/OperationTool:a.onError(L:-1): --> e instanceof ApiException err:com.zhouyou.http.exception.ApiException: 未知错误

大神,我想问一下,我用自定义的bean集成了你的ApiResult,不混淆用的都挺好,混淆了后也添加了你的混淆参数,
但是请求数据返回的json串是对的,到最后就走到未知错误了,请问是哪里没设置好么

经过排查,在ApiResultFunc的ApiResult result = gson.fromJson(json, type);混淆前后,type,json都是一样的,
但是得到的result没混淆就能解析到code,message,混淆后就都是null,求大神解答

**Comment by zhou-you** [comment]
我的混淆也是我代码中那样处理的，没有问题啊，是不是你自己的ben没有避免混淆

**Comment by zhou-you** [comment]
可能混淆没有加全，看我demo里的文档讲解

2017-10-26 14:12 GMT+08:00 yangqqq537 <notifications@github.com>:

**Comment by zhou-you** [comment]
demo里有详细的混淆配置文件

2017-11-13 14:14 GMT+08:00 周游 <zhouyou1989123@gmail.com>:

**Comment by zhou-you** [comment]
混淆我有更新，请查看：https://github.com/zhou-you/RxEasyHttp#混淆

在 2017年11月13日 下午2:14，周游 <zhouyou1989123@gmail.com>写道：
