### ISSUE TITLE
您好，后台请求把错误信息放在了errorbody里面，用了您的框架，走了onError的回调，但是在ApiException里面拿不出errorBody

### ISSUE THREAD

**Issue by StriveCheng** [zhou-you/RxEasyHttp#28]
如题，我们在重复注册的时候，后台把错误信息，放在了errorBody里面，您的框架走了onError回调，请问怎么从ApiException拿出errorBody？

**Comment by zhou-you** [comment]
你好，你的问题，在讨论群里也有人遇到，已经解决了，请在群里提问，会帮你解决的。这里不好描述，谢谢！

**Comment by coderhou** [comment]
if (e.getCause() instanceof HttpException) 
HttpException httpException = (HttpException) e.getCause();
httpException.response().errorBody().string()

楼主提供的解决办法！
