### ISSUE TITLE
错误处理

### ISSUE THREAD

**Issue by RuffianZhong** [zhou-you/RxEasyHttp#29]
请教一个问题，框架中返回数据支持泛型，我们理想中的返回数据是：
{code:1,msg:"success",data:{age:1,name:"zhangsan"}}
当结果返回的数据为：
{code:0,msg:"error",data:“error”}
或者
{code:0,msg:"error",data: [] }
的时候处理会出错吗？就是当后台返回的数据不是规则的，成功和失败data的数据类型不一致的时候，你怎么处理的？

2.另外一点：关于上传下载，如果能加入断点续传就很完美了，看文档介绍，这个库唯一的不足就是这个了。不一定要直接封装到库中，可以分开一个库来引用，项目有需要的再引入上传、下载库。希望作者可以考虑一下，我会持续关注

**Comment by zhou-you** [comment]
当后台返回的数据不是规则的，方案一：通过自定义数据结构ApiRestult来解决。方案二：如果数据结构还是比较特殊就是针对任意bean的，目前还不支持。可以返回String自己外面解析。


上传下载的，我没考虑是因为，上传下载这个功能如果做深了也是很重的，包括断点下载、后台服务、下载管理、多线程、多任务等。不想把网络库做的太重，也有很多app是不需要下载管理模块的，只是简单的上传图片、下载apk等基础功能。不过你的建议会考虑的。

**Comment by RuffianZhong** [comment]
@zhou-you 
是的，当后台返回数据不规则的时候，使用gson解析会报类型错误，所以到最后我就返回String来解决通用的问题。
大文件上传下载确实不是刚需，所以我建议你能再做一个库，让你的这个网络库能够依赖下载库，当有需要的开发者可以直接添加，那么这样一套框架几乎就很完美了。只是建议，用有限的时间做最有的事情就好了。

**Comment by zhumj** [comment]
数据解析兼容这方面太差了

**Comment by zhou-you** [comment]
数据解析方面我会继续扩展的


2017-11-18 12:21 GMT+08:00 zhumj <notifications@github.com>:
