### ISSUE TITLE
大神什么时候出Rxjava2 的？

### ISSUE THREAD

**Issue by feisher** [zhou-you/RxEasyHttp#3]

**Comment by zhou-you** [comment]
我尽量早点出

**Comment by jikyeah** [comment]
@zhou-you 一直期待着，出Rxjava2版，马上用！加油！

**Comment by zhou-you** [comment]
Rxjava2已经出来了

2017-08-04 11:53 GMT+08:00 jikyeah <notifications@github.com>:

**Comment by jikyeah** [comment]
@zhou-you 给力，必须点赞！

**Comment by feisher** [comment]
+1024  (￣▽￣)" @zhou-you
