### ISSUE TITLE
放弃此框架的各种理由，希望作者完善

### ISSUE THREAD

**Issue by 1060680253** [zhou-you/RxEasyHttp#30]
希望开源作者完善以下坑点：
# **_**1.无法获取完整的Response对象，从而无法获取相应的header  ；**_**
阐述：这个功能没有，多么可怕；如果前台是通过获取响应头部的cookie从而实现登录态，那么使用这个框架绝壁垮掉；当使用到服务器时间时，本可以从头部获取服务器时间，结果又是绝壁垮掉

# **2.不能获取返回json转化的第一个直接对象，非要指定获取对应泛型属性。这让我在做微信第三方登录浪费很多时间，自己尝试改框架，但是时间确实紧急，让我放弃；**
阐述：这个功能没有，多么可怕；当后台将部分数据放置于code，data从一层上，那么又是绝壁垮掉；或者想微信第三方登录，其响应数据不遵从code，data这样的格式，而我原本就是获取第一层数据，那么又是绝壁垮掉；

# **3.在定义ApiResult的isOK方法，直接定死0是ok，无法自定义**
阐述：这个功能没有，多么可怕；后台给我定义，1是成功，其他都是失败，具体失败原因放置msg中，那么又是绝壁垮掉；当我进行跨域访问，这个服务器认为1是成功，那个服务器认为0是成功，那么又是绝壁垮掉；

**Comment by yulinyige** [comment]
1. cookie 是可以获取得到的, 认真看文档. 不过现在有一个逻辑错误, 在 issue 中有提到, 自己修改一下.
2.  可以自定义 CallBack.  可以自己解析 JSON 对象.
3, ApiResult 的 code 可以自定义
最好的方法是: 添加源码到项目, 而不是依赖, 然后自己改动源码.

**Comment by zhou-you** [comment]
感谢 “1060680253  ”的反馈，但是反馈问题请从正面出发，不要带有负面的一些东西，看清事物的本质，仔细阅读文章的讲解和用法，对自己和对他人都有好处，不管学习什么不可能立马就上手，除非自己本身的功底很硬。关于你的问题想做以下说明：
1.本网络库是支持全局和局部设置header的，他是通过拦截器来使用，cookie 也是支持的，也有很多网友已经实现了该功能，你可以定义一个头部拦截器来处理cookie ，更通用。

2.为什么药指定获取对应泛型属性呢，是因为app开发中如果你的后台是有一个统一标准的，你会发现code、msg、data等都是固定的，真正关系界面显示的是data。这么设计师为了方便易用，只关心有用的数据部分。但是你的自定义数据结果不一致，可以通过自定义数据结构来解决。或者你不怕麻烦，可以直接返回String自己完全解析。另外时间确实紧急，让我放弃！这个是你自己的问题，我觉得这不是一个正当的理由，与其抱怨别人，为什么不反思自己，是不是还有东西没掌握，理解不到位，加强自己的学习能力。

3.ApiResult是库中默认的一个数据结构，code=0表示成功，所有isOk模式是0表示成功，但是可以通过自定义数据结构来改变isOk的，wiki文中有有介绍！有介绍！有介绍！

**Comment by amber-yi** [comment]
其实最好的就是克隆下来，然后根据自己需求改，作者思路很好，但是轮子在数据结构对接不上的情况下上手不容易，有时间的话可以copy代码自己研究
