### ISSUE TITLE
Cookie 获取不到

### ISSUE THREAD

**Issue by yulinyige** [zhou-you/RxEasyHttp#31]
我在 Application 中设置了全局的设置. 如下:
 EasyHttp.getInstance()
                .setBaseUrl(URL.API_HOST)
                .setCookieStore(new CookieManger(this))  // 一定要打开 Cookies 支持
                .debug("HTTP", true)
                .addCommonHeaders(headers);

然而, 在请求API后获取 cookies, 获取不到数据, 请问这是 Bug 吗? 还是我设置有问题呢 ?

**Comment by yulinyige** [comment]
我 Debug 了一下, 是 PersistentCookieStore.java 文件逻辑上有问题. 
其中 
`public void add(HttpUrl url, Cookie cookie) {
        String name = getCookieToken(cookie);
        if (cookie.persistent()) {
            if (!cookies.containsKey(url.host())) {
                cookies.put(url.host(), new ConcurrentHashMap<String, Cookie>());
            }
            cookies.get(url.host()).put(name, cookie);
            SharedPreferences.Editor prefsWriter = cookiePrefs.edit();
            prefsWriter.putString(url.host(), TextUtils.join(",", cookies.get(url.host()).keySet()));
            prefsWriter.putString(name, encodeCookie(new SerializableOkHttpCookies(cookie)));
            prefsWriter.apply();
        } else {
            if (cookies.containsKey(url.host())) {
                cookies.get(url.host()).remove(name);
            }
        }
    }`
add 方法默认只对 Expires 为 false, 即永远不过期的 cookie 保存, 当 Expires =true 时, 就没有进行 Cookie 进行保存.  应该改为:
`public void add(HttpUrl url, Cookie cookie) {
        String name = getCookieToken(cookie);
        // 添加 host key. 否则有可能抛空.
        if (!cookies.containsKey(url.host())) {
            cookies.put(url.host(), new ConcurrentHashMap<String, Cookie>());
        }
        // 删除已经有的.
        if (cookies.containsKey(url.host())) {
            cookies.get(url.host()).remove(name);
        }
        // 添加新的进去
        cookies.get(url.host()).put(name, cookie);
        // 是否保存到 SP 中
        if (cookie.persistent()) {
            SharedPreferences.Editor prefsWriter = cookiePrefs.edit();
            prefsWriter.putString(url.host(), TextUtils.join(",", cookies.get(url.host()).keySet()));
            prefsWriter.putString(name, encodeCookie(new SerializableOkHttpCookies(cookie)));
            prefsWriter.apply();
        } else {
            SharedPreferences.Editor prefsWriter = cookiePrefs.edit();
            prefsWriter.remove(url.host());
            prefsWriter.remove(name);
            prefsWriter.apply();
        }
    }`

**Comment by zhou-you** [comment]
你好，已经按照你的方式处理
