### ISSUE TITLE
HttpLoggingInterceptor 可不可以自己设置打印等级？

### ISSUE THREAD

**Issue by jingzz1** [zhou-you/RxEasyHttp#32]
看了源代码，打印等级是默认INFO：
 public void log(String message) {
        logger.log(java.util.logging.Level.INFO, message);
    }

但INFO等级太低，干扰信息太多，我想改成最高等级的SEVERE，但貌似没办法改。

**Comment by zhou-you** [comment]
这个调试信息 不能设置的，我可以提供一个设置的方法，但是默认打印的信息都是很必要的呢，方便分析问题
