### ISSUE TITLE
自定义ApiResult解析不出来

### ISSUE THREAD

**Issue by jingzz1** [zhou-you/RxEasyHttp#33]
数据结构是

    {   "error_code":0,
         "reason":"Succes",
         "result":"……"
    }

    于是我自定义了ApiResult

    public class ApiResult<T> {
        private String reason;
        private int error_code;
        private T result;
    }

    使用的时候这样用：
          .
    execute(new SimpleCallBack<ApiResult<ResultBean>>() {
        @Override
        public void onError (ApiException e){

        }

        @Override
        public void onSuccess (ApiResult < Bean > beanApiResult) {

        }
    });

    结果都是：
    NullPointerException
            解析不出来

**Comment by zhou-you** [comment]
你好，请看下自定义数据结构ApiResult的讲解，你自定义的ApiResult，不全，导致解析不到数据。如果解决不了请加群提问，会帮你解决的。
