### ISSUE TITLE
数据解析+错误回调ApiException为null

### ISSUE THREAD

**Issue by zhumj** [zhou-you/RxEasyHttp#34]
1、数据解析兼容这方面太差了，如果每个接口返回String来解决通用的问题，那每个请求就还需要在外面对code进行判断是否请求成功，因为我打印结果直接是 “{code:1,msg:"success",data:{age:1,name:"zhangsan"}}” 这样的一个字符串，而不是把 “data” 的数据转换为String类型回传，这很繁琐，还不如直接把数据解析去掉还能减少一些包的大小呢。
2、还有ApiRestult替换太麻烦。
3、最后还有一个错误回调ApiException没有返回的问题，虽然onError(e: ApiException)方法调用了，但是ApiException为空。
希望这几个问题能改善一下

**Comment by zhou-you** [comment]
1.数据解析这块库里是有默认的数据结构，如果数据结构不正确可以自定义数据结构。
2.ApiResult替换太麻烦？这个值需要简单的继承，覆写自定义的就可以了。假如你的应用有100+个接口，是每个接口都自己去写解析复杂麻烦呢？还是花时间研究自定义ApiRestult，弄懂一个，其它99+共用，这个请自己评估。
3.错误了ApiException为空，还从来没有人反馈过呢，请详细描述下，是空指针，还是？？

**Comment by zhumj** [comment]
1/2. 你说的默认数据结构就是 ApiResult 吧，但是我继承这个之后返回结果还是不能解析，何解
3.在数据解析错误的时候 onError(e: ApiException) 没调用

**Comment by zhou-you** [comment]
应该不会出现你说的这个情况呢，是不是哪里用的不正确，有很多人都在使用了，如果有这个问题早就反馈出来了，可以加群更好的解决问题。
