### ISSUE TITLE
ApiResultFunc类中Json解析问题

### ISSUE THREAD

**Issue by JiaoPengJob** [zhou-you/RxEasyHttp#36]
当接口返回的json数据为object时，会报异常：java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 22 path $.result
Log异常信息位置为：at com.zhouyou.http.func.ApiResultFunc.apply(ApiResultFunc.java:83)
建议添加一种直接解析object的方式，而不是tostring（）之后才进行转换。

**Comment by zhou-you** [comment]
这个是你自定义数据结构解析的问题，否则不会出错的，很多人都已经在使用。
