### ISSUE TITLE
加密的话从哪里插入？

### ISSUE THREAD

**Issue by profei** [zhou-you/RxEasyHttp#37]
现在流行的aes+rsa  或者des+rsa加密  怎么在流程里插入
自己再写一个拦截么？

**Comment by zhou-you** [comment]
统一处理的话可以加一个全局拦截器，可以在签名、token等拦截器中一块处理

**Comment by profei** [comment]
谢谢 加密拦截测试通过了

**Comment by zhou-you** [comment]
ok,有问题再反馈
