### ISSUE TITLE
bean生成出错

### ISSUE THREAD

**Issue by chenhao1041661180** [zhou-you/RxEasyHttp#38]
使用ProgressDialogCallBack 或ProgressSubscriber方式，传入我要得到的bean。但是返回的结果中 bean对象一直为null.不知道怎么该怎么解决

**Comment by zhou-you** [comment]
请查看自定义数据结构部分，看看你的数据结构和我默认是是否一致，不一样的需要自定义

**Comment by zhou-you** [comment]
请查看是不是数据结构导致的，或者解析bean的字段不对

2017-11-29 16:26 GMT+08:00 chenhao1041661180 <notifications@github.com>:
