### ISSUE TITLE
bean

### ISSUE THREAD

**Issue by summertravel** [zhou-you/RxEasyHttp#39]
public class LoginBean{

    /**
     * uid : 1
     * state : 1
     */
    public String uid;
    public String state;
    public String message;
}
返回 的是 EasyHttp:  body:{"uid":"1","state":1}
下边是用的：
  EasyHttp.post(Constants.LOGIN_URL)
                .params("name",etName.getText().toString())
                .params("pwd",etPwd.getText().toString())
                .execute(new SimpleCallBack<LoginBean>() {
                    @Override
                    public void onError(ApiException e) {

                    }

                    @Override
                    public void onSuccess(LoginBean loginBean) {
                        if(loginBean.state.equals("1")){
                            startActivity(new Intent(LoginActivity.this,ProjectsActivity.class).putExtra("uid", loginBean.uid));
                        }
                        else {
                            showToast(loginBean.message);
                        }
                    }
                });
这是日志
E/EasyHttp:BaseSubscriber.onError(L:69): -->http is onError
:BaseSubscriber.onError(L:71): --> e instanceof ApiException err:com.zhouyou.http.exception.ApiException: NullPointerException

**Comment by summertravel** [comment]
是哪里用得不对么

**Comment by kangjinwen** [comment]
楼主,你这个问题是怎么解决的?哪里用的不对?我也是这样的错误

**Comment by summertravel** [comment]
我记得是这个SimpleCallBack的用法问题

**Comment by zhou-you** [comment]
数据结构不一致需要采用自定义数据结构，请看wiki里面的讲解，注意查看文档，如果还是解决不了请加群
https://github.com/zhou-you/RxEasyHttp/wiki/ApiResult_New
