### ISSUE TITLE
callback的T只能用string来接收？

### ISSUE THREAD

**Issue by summertravel** [zhou-you/RxEasyHttp#40]
用bean接受报错

http is onStart
BaseSubscriber.onError(L:69): -->http is onError
BaseSubscriber.onError(L:71): --> e instanceof ApiException err:com.zhouyou.http.exception.ApiException: NullPointerException

**Comment by kangjinwen** [comment]
楼主,你这个问题是怎么解决的?哪里用的不对?我也是这样的错误
