### ISSUE TITLE
如何通过 HttpParams 提交数组

### ISSUE THREAD

**Issue by yulinyige** [zhou-you/RxEasyHttp#43]
服务器支持数组, 但是 HttpParams 无法提交数组, 阅读代码发现 HttpParams 是通过 LinkedHashMap 存储参数的, 当加入数组时, 就会把前面的覆盖掉. POST 方式, 如何做到提交数组呢 ?

**Comment by zhou-you** [comment]
你好，post提交 数组到后台，这种方式比较少，但是你可以参考：http://ask.csdn.net/questions/263133

**Comment by zhou-you** [comment]
提交数组是一个比较麻烦而且比较少见的方式，关于post提交数组，你可以百度一下

2017-12-26 8:48 GMT+08:00 yulinyige <notifications@github.com>:
