### ISSUE TITLE
解析的问题

### ISSUE THREAD

**Issue by AIlll** [zhou-you/RxEasyHttp#45]
比如：{"err_code":0,"err_msg":"Success","data":null}。
自定义ApiResult后，如果服务器返回的data为null，并且ApiResult传入的泛型是bean对象的话，解析会报空指针。如果泛型传入的String，那么该json字符串被会直接返回，ApiResult也不判断Code，不管Code是多少，都走成功的回调

**Comment by zhou-you** [comment]
"data":null    这个是因为Rxjava2 onNext不能为空，所有当成错误在onError里返回空指针异常，“如果泛型传入的String，那么该json字符串被会直接返回，ApiResult也不判断Code，不管Code是多少，都走成功的回调”这个就是这样的，没有判读code，为了灵活性，其它非ApiResult结构的，也能使用String整体返回。

**Comment by zhou-you** [comment]
所以这个需要自己处理下

**Comment by AIlll** [comment]
@zhou-you 后台数据返回不变动的话，data为null的情况如何处理，可否给点意见

**Comment by zhou-you** [comment]
目前这个没有特别好的办法处理，最成功的做法是Rxjava2能允许onNext返回null,目前有其它方式处理，但是代价很大，建议目前暂时还是在onError里如果是空指针异常，就认为是请求成功了，只是返回数据为null而已
