### ISSUE TITLE
请教：如何统一处理OnError中返回的错误信息。

### ISSUE THREAD

**Issue by 1226362423** [zhou-you/RxEasyHttp#47]
有什么方法可以统一捕获一个服务器返回的一个特定错误，比方说token 错误，需要重新登录。

**Comment by 1226362423** [comment]
还请教下：Onerror报1010    e instanceof ApiException err:com.zhouyou.http.exception.ApiException: NullPointerException  怎么回事啊

**Comment by zhou-you** [comment]
设置一个全局拦截器，在拦截器里面处理，如果是token 错误可以refreshtoken处理，发出消息给到外面即可。
