### ISSUE TITLE
ApiResultFunc 文件 Type 传入 String 类型都是把 responseBody 直接返回了

### ISSUE THREAD

**Issue by zhumj** [zhou-you/RxEasyHttp#49]
ApiResultFunc 文件的 apply(@NonNull ResponseBody responseBody) 方法里面，不管是 自定义 ApiResult 还是 默认 ApiResult 传入 String 类型的时候都是把 responseBody 直接返回了，这是一个问题哟

**Comment by zhumj** [comment]
而且请问 默认ApiResult 是什么情况会进入？我不管使用框架自带的ApiResult还是自己继承的ApiResult的模型都是走的 自定义ApiResult

**Comment by zhou-you** [comment]
apply是一定会进去的，当传入String类型，是没有对code做判断，默认返回所有的的内容

**Comment by wyj365372704** [comment]
CallClazzProxy<CustomApiResult<T>, T>   ,当泛型为String时返回的是整个body结果字符串，可是我们想要T result  的类型就是String  哪该怎么办？

**Comment by zhou-you** [comment]
当使用String类型返回时是返回整个body，是不需要用代理的。当初是有设想过要返回需要内容String的也就是T,但是这样和返回所有String比较混淆，也太个性，就默认返回所有的，如果自己需要，自己在处理下
