### ISSUE TITLE
如何自动转换不符合统一的数据结构（code、msg、data）的自定义类型

### ISSUE THREAD

**Issue by tcqq** [zhou-you/RxEasyHttp#52]
在这里目前测得不管是用哪种Callback进行调用，都未能行得通。如下代码可以正常以字符串形式获取服务器返回的数据，然后进行手动转换为对象：

![tim 20180303040302](https://user-images.githubusercontent.com/10644057/36919298-c6e206e2-1e97-11e8-9183-c9103d473b6c.png)

然后发现所有的execute() 方法好像都用到了ApiResult类，所以不知道要怎么转化我自己的自定义类。

![tim 20180303041457](https://user-images.githubusercontent.com/10644057/36919833-9e8125a0-1e99-11e8-80f2-fbea041cf38e.png)

所以我想问

1. EasyHttp是否能够将自定义的类型自动转换？怎么转换？
1. [看到其它issue里有回答](https://github.com/zhou-you/RxEasyHttp/issues/30)，自定义 CallBack 来自己解析 JSON 对象，但是我没有想到如何自定义Callback来解析？我应该怎么样做才行？

谢谢。

##
## 成功时服务器返回的 json data(成功时没有`错误码`和 `消息`): 
`
{
    "id": "123456",
    "userName": "test",
    "email": "test@example.com",
    "favoriateBooks": [ {
           "id": "9-787-653-2332-0",
           "author": "Donald J. Trump",
           "publishedDate": "2018-01-01"
     }]
}
`
## 错误时服务器返回的 json data: 
`
{
    "error":{
        "errors":[
            {
                "domain":"usageLimits",
                "reason":"keyInvalid",
                "message":"Bad Request"
            }
        ],
        "code":400,
        "message":"Bad Request"
    }
}
`

**Comment by zhou-you** [comment]
这种结构不是标准的数据结构，成功和失败的时候json 都不一样，即使有自动转换也很麻烦，最简单的方式i就是返回String，自己解析。

在 2018年3月3日 上午4:46，tcqq <notifications@github.com>写道：

**Comment by tcqq** [comment]
## 如果不改变，这个库最后的结果是被替代，代表这之前的努力全部白费。

#### "这种结构不是标准的数据结构"
-现在Google，Github的数据结构就是这样，许多经验丰富的开发人员可以看到这种数据结构的好处，我不做更多的解释。

#### "即使有自动转换也很麻烦，最简单的方式i就是返回String，自己解析。"
-这不会发生，因为现在自动解析JSON是网络请求库的标配，如果无法实现，使用这个库的项目将存在大量的重复和模板代码。

## [Google data format: ](https://developers.google.com/books/docs/v1/reference/mylibrary/bookshelves/get):
![image](https://user-images.githubusercontent.com/10644057/37075599-8eb86814-220d-11e8-8a9e-a15a9f0c47d5.png)
![image](https://user-images.githubusercontent.com/10644057/37075624-af1df31c-220d-11e8-9f7b-679e0f755fdd.png)

## [Github data format: ](https://api.github.com/users/tcqq)

![image](https://user-images.githubusercontent.com/10644057/37075688-f5242cf0-220d-11e8-9942-ea969687f16f.png)
![image](https://user-images.githubusercontent.com/10644057/37075692-f948c08e-220d-11e8-9375-0d733a2a7f3a.png)

**Comment by DaiFalin** [comment]
如果您对这种不标准的json数据有更好的解决方案，你可以提出来，如果没有解决方案，又想用别人的轮子，那就只能适应别人方式了。

**Comment by tcqq** [comment]
@DaiFalin 
“如果您对这种不标准的json数据”
-我在上面发送的数据结构分别是Google和Github的数据结构，你是在说Google和Github的数据结构不标准吗？

“有更好的解决方案你可以提出来，如果没有解决方案，又想用别人的轮子，那就只能适应别人方式了。”
-我已经将方案发送给作者了。

**Comment by DaiFalin** [comment]
@tcqq 你非要钻牛角尖，那就说json格式不统一可以吗？你有更好的方案可以开源出来啊，作者只能满足一部分人的需求，不能满足所有人，你觉得这个方式不好，你可以不用，或者拿出更好的方案。

**Comment by DaiFalin** [comment]
@tcqq json格式不统一，这样说可以吗

**Comment by tcqq** [comment]
@DaiFalin 没有规定，如果JSON格式不统一，它就是不好的。

**Comment by tcqq** [comment]
@DaiFalin Google和Github的JSON格式是统一的，它只返回有用的数据。

**Comment by lpy19930103** [comment]
@tcqq 你好，可以给我发下你的解决方案么，我觉得只返回有用的数据是正确的

**Comment by yfhy** [comment]
zhou-you 大佬,我想提个建议,ApiResult能不能定义成interface类型,因为很少的用户和你的json格式一样,定义成interface,就必须定义自己的Result来继承ApiResult,通过Callback泛型传入自定义的类型,减少使用疑惑.

针对tcqq大佬提的这种格式,我看响应的statusCode不是正常的200,而分别是400和404,有个简单办法,在ApiResult里添加方法setStatusCode,自定义Result里可根据statusCode来重写isOk方法.还不行就再继续扩充ApiResult里的方法,应该能解决的.

**Comment by zilianliuxue** [comment]
若返回的是加密的数据，那是不是要对字符串这个保留，把返回的结果可以自己处理

**Comment by zhou-you** [comment]
若返回的是加密的数据，可以用拦截器统一处理后再返回到上层。

**Comment by 844189873** [comment]
我也遇到了类似的问题，现在的ApiResult是interface类型，但是依然解决不了返回的数据格式不统一问题。
例如，成功时返回:
{
code:200,
data:xxx
}

失败时返回:
{
code:xxx,
msg:xxx
}

由于失败时没有返回data节点，结果用这个库就报错了，尝试过自己在ApiResult<T>的getData方法的时候，如果是null则new一个对象返回，但由于取不到范型T的具体类型，最终没有成功。

已有的接口都是在失败时不返回data节点的，有没什么方法解决这个问题呢？

**Comment by zhou-you** [comment]
data不能为null这个也是Rxjava2 onNext不能返回null的蛋疼问题，如果你想满足你描述的这个结构，是有办法解决的，但是稍微麻烦一点，尽量将错误和成功定义成同一种数据类型，例如 data为 某个bean,如果错误时可以在你自定义数据结构中 建一个错误的bean返回回来
