### ISSUE TITLE
返回数据字段data为null时，空指针异常

### ISSUE THREAD

**Issue by heyyue** [zhou-you/RxEasyHttp#53]

**Comment by zhou-you** [comment]
这个是Rxjava2的一个问题 onNext不能为null，所以不能在onSuccess里返回，返回到错误里面去了，需要你自己处理一下

**Comment by wyj365372704** [comment]
这一块我觉得库可以修改一下让json解析的时候当data为null时,data容器对象=null,而不是粗暴的抛到onError回调中去.

**Comment by JacksenLaw** [comment]
自定义APIResult之后一直返回NullPointerException，查看了很多次，都没发现问题

**Comment by zhou-you** [comment]
你可以加群，针对问题具体分析
