### ISSUE TITLE
put 异常 

### ISSUE THREAD

**Issue by adasdasdadweq** [zhou-you/RxEasyHttp#58]
log : body: maybe [file part] , too large too print , ignored!

upJson(json)
.execute(json)

不知道是调用姿势问题，还是库的问题，提个issue，望作者能解答下

**Comment by zhou-you** [comment]
这个是okhtttp的错误，请遵循okhttp的要求，或者百度查找okhttp的这个相关错误，这个错误与库没有关系。

**Comment by adasdasdadweq** [comment]
那能问下这个库 put 的调用例子，req body 应该如何设置，

**Comment by zhou-you** [comment]
apiManager.putBody(url, object);

**Comment by zhou-you** [comment]
文档应该有put讲解 传递body的  ，这里的body是直接对应的object
