### ISSUE TITLE
RxCache什么时候会单独出开源项目啊？期待~~

### ISSUE THREAD

**Issue by HolenZhou** [zhou-you/RxEasyHttp#63]

**Comment by zhou-you** [comment]
如果大家对这个需求比较多，我会认真考虑的，之前有想单纯出来的想法，但是不知道大家有没有这个需求，所以一直没弄。

**Comment by HolenZhou** [comment]
正好我的项目中需要用到这样的框架，所以这几天我借鉴了RxEasyHttp中的缓存部分的代码封装了一个RxCache的库：https://github.com/HolenZhou/rxcache，已经注明借鉴于此项目，但目前仅仅满足了我项目中的需求，其他人如有兴趣可参考~
