### ISSUE TITLE
如何避免多个网络请求中出现多次网络请求提示加载框

### ISSUE THREAD

**Issue by dapengko1** [zhou-you/RxEasyHttp#70]
请问下作者，在有多个网络请求的时候，每个网络请求都有加载提示框，这样就会显示多个提示框，怎么做到只显示一个提示框？除了用Rxjava的方法。

**Comment by zhou-you** [comment]
1.采用Rxjava方法就是合并请求 2.不用Rxjava就是在每个请求的时候判断对话框是否已经展示isShow()，已经展示了就不弹出，但是消失处理会比较麻烦。
