### ISSUE TITLE
感谢分享，但是如何使用这个框架请求webservice接口

### ISSUE THREAD

**Issue by VainAnts** [zhou-you/RxEasyHttp#74]

**Comment by zhou-you** [comment]
库目前不支持，demo也没提供，但是是有办法支持的。
1.引入compile("com.squareup.retrofit2:converter-simplexml:2.0.0-beta3")
2.配置.addConverterFactory(SimpleXmlConverterFactory.create(serializer))
3.请求用@Body  所有参数封装在Body里面，不能用库提供的params
4.用String返回，自己解析
