### ISSUE TITLE
缓存问题

### ISSUE THREAD

**Issue by frinda** [zhou-you/RxEasyHttp#78]
CacheAndRemoteDistinctStrategy 和 CacheAndRemoteStrategy，如何网络数据有更新的话，缓存和网络的数据都会显示，应该只显示最新数据

**Comment by zhou-you** [comment]
你读下你反馈的问题，别人能明白你说的意思不，CacheAndRemoteDistinctStrategy 要想能够判读是否更新 bean 一定要重写tostring（）方法

**Comment by frinda** [comment]
不好意思，是我的问题，没把问题说清楚，针对CacheAndRemoteDistinctStrategy这种加载数据的方式，如果网络数据有更新的话，distinctUntilChanged这种过滤数据的方式不会起作用，势必会把网络数据和缓存数据多会返回

**Comment by zhou-you** [comment]
CacheAndRemoteDistinctStrategy 如果有数据更新的话，肯定是返回两次，缓存一次，网络数据一次。distinctUntilChanged能起作用是 你请求的数据bean  以及bean里面包含的bean，都要重写tostring（）,请看我的demo里面是怎么做的，bean的toString是怎么写的，参照！
