### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by frinda** [zhou-you/RxEasyHttp#79]
BaseRequest类里的genernateRetrofit函数如果每次返回的Retrofit.Builder时都取自EasyHttp.getRetrofitBuilder()返回，由于EasyHttp是单例存在的(EasyHttp.getRetrofitBuilder()也是单例的)，那么在build函数每次调用都会addCallAdapterFactory(RxJava2CallAdapterFactory.create()),这样Retrofit里面的adapterFactories就会有很多个RxJava2CallAdapterFactory的实例，建议在build函数里处理一下

**Comment by zhou-you** [comment]
好我会关注下这个问题

**Comment by zhou-you** [comment]
你好，非常感谢你的反馈，问题已优化。
