### ISSUE TITLE
enum问题

### ISSUE THREAD

**Issue by Reginer** [zhou-you/RxEasyHttp#8]
库太屌了，但是发现其中有用到枚举的地方，不知道楼主能不能使用其他方式替换一下。

**Comment by zhou-you** [comment]
你好，你是觉得枚举不好用吗？欢迎探讨

**Comment by Reginer** [comment]
是啊，降低性能并且增加体积 。感觉这么好的库用枚举还可以优化。
刚才找了两篇文章，一个详细说问题，另一个是主要如何替换，楼主参考一下。
http://blog.csdn.net/young21234/article/details/49962659

http://blog.csdn.net/u013598660/article/details/51105035

**Comment by zhou-you** [comment]
好的，谢谢你的建议，我会考虑优化的
