### ISSUE TITLE
断网条件下重复回调缓存

### ISSUE THREAD

**Issue by xiongxiaosong** [zhou-you/RxEasyHttp#81]
断网的时候，如果设置了重试次数，比如3次，会重复回调三次缓存数据回来

**Comment by zhou-you** [comment]
这个是这样的，需要你上层处理，根据自己的需要：1，在断网的时候就不去请求  2.在请求的结果中，判断是否是来自缓存，如果判断来自缓存，在文档缓存篇中有讲解。或者来一次添加后就不要。3.设置缓存次数放在当前请求中.retryCount(是否有网？3:0)；不建议在全局中对所有请求都进行重试操作，根据需要对个别接口进行重试设置。
