### ISSUE TITLE
nullException 

### ISSUE THREAD

**Issue by GavinDon** [zhou-you/RxEasyHttp#82]
按照wiki中的步骤配置开始请求，只提示了一个nullException 这是哪里的提示？？

![Uploading image.png…]()

**Comment by zhou-you** [comment]
请看是不是数据结构不正确导致的

**Comment by GavinDon** [comment]
嗯，是的  后台返回的数据格式不是统一的

**Comment by zhou-you** [comment]
需要你自定义数据结构才行：https://github.com/zhou-you/RxEasyHttp/wiki/ApiResult_New

**Comment by GavinDon** [comment]
不行。 你这个自定义数据 也是定义成标准的返回格式，但是我这个后台返回的
数据结构不是统一的。随心所欲的返回的。

**Comment by zhou-you** [comment]
那只能用String来接收

**Comment by GavinDon** [comment]
算了。。我封装了一个简单的项目中使用的够了。。期待下次更新可以支持这种无节操的反参

> 

>
