### ISSUE TITLE
 java.lang.NullPointerException: baseUrl == null

### ISSUE THREAD

**Issue by MarkRaoAndroid** [zhou-you/RxEasyHttp#85]
不设置baseUrl就报错？？？这设计的不合理吧

**Comment by zhou-you** [comment]
baseurl不能为null主要是因为Retrofit类源码中的build()决定。
![image](https://user-images.githubusercontent.com/15211403/44969071-f7533b80-af7d-11e8-844f-fee6aab0a064.png)
目前我已兼容了这个问题，在我的库中做了修改可以支持baseurl为null。但是在请求的时候需要设置baseurl或者EasyHttp.get(url) 此时url必须是要写全
