### ISSUE TITLE
在回调onSuccess之前，dialog会卡一会不动

### ISSUE THREAD

**Issue by hebinjiayou01** [zhou-you/RxEasyHttp#86]
如题

**Comment by zhou-you** [comment]
你好能够描述详细一点吗，我这里测试dialgo好像没有这个问题，这里没有做特殊操作，只是在开始显示对话框，结束取消对话框，都是异步的操作。

**Comment by zhou-you** [comment]
其它用户好像也没反馈过类似的问题，也有用dialog的。

**Comment by hebinjiayou01** [comment]
request.execute(new ProgressDialogCallBack<String>(mProgressDialog, true, true) {
                @Override
                public void onError(ApiException e) {
                    super.onError(e);//super.onError(e)
                  
                }

                @Override
                public void onSuccess(String response) {
                    //请求成功
                
                }
            });

我是用的这个，主要发生在第一次请求的时候，后面就再也不会发生了，因为我们后台IIS ASP.NET第一次访问总是特别慢，想过是不是这个原因，但无从下手，然后UI进程不应该受到影响

**Comment by hebinjiayou01** [comment]
打过日志，卡的那会没进入到onSuccess，卡完之后就进入onSuccess回调了
