### ISSUE TITLE
The mapper function returned a null value的问题

### ISSUE THREAD

**Issue by xu2012** [zhou-you/RxEasyHttp#87]
当请求成功的时候，如果data字段为空，就会抛出空指针异常，查了半天源码，发现是rxjava中Func的apply方法不能返回空数据所致，希望大佬看看这个问题，怎么优化一哈

**Comment by zhou-you** [comment]
这个问题早就有，从库一开始就知道有这个问题，这个问题不好优化，准备后期优化
