### ISSUE TITLE
缓存模式中的CACHEANDREMOTEDISTINCT问题

### ISSUE THREAD

**Issue by 7hundeR** [zhou-you/RxEasyHttp#92]
缓存模式中的CACHEANDREMOTEDISTINCT在断网的情况会抛出域名解析异常，这个能优化一下吗，在断网情况加载缓存，不抛出这个异常, FIRSTREMOTE模式虽然也能实现，但是每次都会缓存

**Comment by zhou-you** [comment]
这个问题我会关注一下

**Comment by g754687222** [comment]
这个模式的策略还挺好，但onError和onSuccess都会调用，我现在是自己写个变量，如果回调onSuccess，就忽略onError，就是太麻烦。 @zhou-you

**Comment by zhou-you** [comment]
首先要认识到这个问题怎么产生的，断网情况会抛出域名解析异常，这个是Retrofit就是这么设计的，在正常的情况下抛出这个异常也是正确的，但是例如个别情况有这种特殊的小场景，不想提示这个异常，那么就需要自己特殊处理，网上也有很多处理方式例如：https://blog.csdn.net/qq_25412055/article/details/53699859

感觉都不是特别好，或者改动比较大。


本库建议这么使用，自定义一个通用的回调，参考代码如下：

/**
 * <p>描述：自定义网络请求回调callBack</p>
 * 作者： zhouyou<br>
 * 日期： 2017/8/14 15:09 <br>
 * 版本： v1.0<br>
 */
public abstract class CacheSimpleCallBack<T> extends SimpleCallBack<T> {
    private T t;

    @Override
    public  void onSuccess(T t) {
        this.t = t;
    }

    public boolean isNull() {
        if (t instanceof CacheResult) {
            return ((CacheResult) t).data == null;
        }
        return t == null;
    }

}

使用的时候例如：
 .execute(new CacheSimpleCallBack<CacheResult<List<Product>>>() {
                    @Override
                    public void onError(ApiException e) {
                        if (e.getCode() == ApiException.ERROR.UNKNOWNHOST_ERROR) {//无网络异常信息
                            if (!isNull()) {//说明有缓存，那么断网就不要往下执行直接返回 不做任何处理
                               return；
                            } 
                        }
                       //处理错误页面/提示
                    }

                    @Override
                    public void onSuccess(CacheResult<List<Product>> products) {
                        super.onSuccess(products);//这句话不能少
                 }
});

通过这种callback统一处理就会比较简单，上面代码还可以再封装，自己灵活运用就行。
