### ISSUE TITLE
OnError不会自动关闭Dialog

### ISSUE THREAD

**Issue by 7hundeR** [zhou-you/RxEasyHttp#94]
使用的是CacheMode.CACHEANDREMOTEDISTINCT模式

**Comment by zhou-you** [comment]
你看下有没有回调 有回调就会关闭的

**Comment by 7hundeR** [comment]
用了ProgressDialogCallBack回调，打断点走了调试，发现有错误出现的时候走了BaseSubscriber的OnError()，没有走ProgressDialogCallBack的回调，ProgressDialogCallBack的onStart()是走了的

**Comment by zhou-you** [comment]
看看是不是少了super.onError()

**Comment by 7hundeR** [comment]
哈哈是的大佬，感谢
