### ISSUE TITLE
CallBackProxy里怎么判断ApiResult返回的是成功才去解析data

### ISSUE THREAD

**Issue by 7hundeR** [zhou-you/RxEasyHttp#95]
我们后台接口返回的不规范，经常数据正确的时候返回的data是对象，错误的时候返回的是数组，他那边不好改让我去兼容(ApiResult的isOk()为true的时候才去解析data，否则不解析data)，我看了CallBackProxy的源码，有点不太明白，大佬能指点下吗

**Comment by zhou-you** [comment]
文档自定义数据结构有讲解的

**Comment by 7hundeR** [comment]
我重写了isOk方法，刚刚看了下源码，发现`HandleFuc`这个类判断了isOk，`PostRequest`的`execute(CallClazzProxy<? extends ApiResult<T>, T> proxy)`方法用的是`ApiResultFunc`，没有判断isOk

**Comment by zhou-you** [comment]
统一再HandleFuc中判断的，ApiResultFunc直管数据解析

**Comment by 7hundeR** [comment]
这个`HandleFuc`类只有`CustomRequest`和`RxUtil`这两个类调用了，`RxUtil`的`ObservableTransformer`被`PostRequest`的`public <T> Disposable execute()`和`public <T> Observable<T> execute()`方法调用了,但是没走`observable.compose(new ObservableTransformer<CacheResult<T>, T>() `，下面有截图
![wechateb2a2a33775003a58c5c45c53841f61a](https://user-images.githubusercontent.com/13944095/48528560-7c39ca00-e8ca-11e8-9ff8-ae5fec08b736.png)

**Comment by zhou-you** [comment]
这里面比较复杂，一两句话也说不清楚，里面有用到反射处理getRawType()等判断
