### ISSUE TITLE
请问大佬 getData() 返回null  或者 后台没有返回data字段 报空指针 怎么处理呢

### ISSUE THREAD

**Issue by GuZhC** [zhou-you/RxEasyHttp#96]
我想就算data = null  只要code是成功码  就走成功回调

**Comment by zhou-you** [comment]
这个存在这个问题是Rxjava2 onNext不允许返回null导致的，需要在错误里面判断下，或者自定义一个callback如果是空指针错误都让走成功，就不用每个请求都处理。

**Comment by 844189873** [comment]
同样遇到了这个问题，框架能不能把这个处理放到自定义ApiResult里面去呀？

**Comment by zhou-you** [comment]
如果定义到ApiResult里面，数据结构会变复杂，需要在用一个对象包裹住data，才能解决data为null引起的Rxjava2 onNext不允许返回null导致的
