### ISSUE TITLE
e instanceof ApiException err:com.zhouyou.http.exception.ApiException: 未知错误

### ISSUE THREAD

**Issue by 377376701** [zhou-you/RxEasyHttp#97]
RxEasyHttp: <-- 200 OK https://api.douban.com/v2/movie/in_theaters?city=广州&start=0&count=10&appId=10101
10-08 10:55:37.399 16327-17100/com.zhouyou.http.demo I/RxEasyHttp: <-- END HTTP
10-08 10:55:37.415 16327-16327/com.zhouyou.http.demo E/RxEasyHttp:BaseSubscriber.onError(L:69): -->http is onError
10-08 10:55:37.417 16327-16327/com.zhouyou.http.demo E/RxEasyHttp:BaseSubscriber.onError(L:71): --> e instanceof ApiException err:com.zhouyou.http.exception.ApiException: NullPointerException

你好，这是什么原因导致的呢

**Comment by zhou-you** [comment]
这个看下是不是返回的data数据为null了，Rxjava2 onNext（）不允许返回数据为空，这种需要在onError里特殊处理下。
